### ISSUE TITLE
Create a plugin for batch converting LZ77 -> ExtendedLZ77 compression for any file

### ISSUE THREAD

**Issue by Ebola16** [libertyernie/brawltools#104]
- [x] Batch Convert (LZ77 compression to ExtendedLZ77), including non-root ARC entry nodes
- [x] Optional subfolder inclusion
- [x] Original LZ77 files will be renamed after creating ExtendedLZ77 files and kept as a backup.
("name.extension" would become "name.extension.original-lz77")

Adding a "Batch Convert (LZ77 compression to ExtendedLZ77)" plugin for any file if, and only if, the compression is set to LZ77 would be extremely useful for saving space. Space saving is becoming more and more important until Dolphin Emulator gains SDHC emulation.

**Comment by libertyernie** [comment]
Would it be for batch conversion, like the other plugin?
Maybe there should be a thread on KC:MM for plugins like these.

**Comment by Ebola16** [comment]
Yes, and the subfolder option would also be useful.

**Comment by Ebola16** [comment]
Also, the problem of identical filenames after conversion would need to be addressed. Perhaps renaming the original LZ77 file to something else and giving the original file name to the new ExtendedLZ77 file will work.

My idea:
Yes/no prompt: Original LZ77 files will be renamed after creating ExtendedLZ77 files. Proceed?
("name.extension" would become "name.original.extension")

I haven't noticed any drawbacks with ExtendedLZ77 but we shouldn't offer to delete the original LZ77 files unless we're absolutely sure that ExtendedLZ77 won't cause any problems. This script would likely reveal ExtendedLZ77 problems after using it.

Additionally, I can't think of any good reason for the opposite process, convert ExtendedLZ77 to LZ77, so that probably isn't needed.

**Comment by libertyernie** [comment]
All LZ77 files will be .pac, right?
I'm thinking the plugin should look for *.pac files, but ignore *.original.pac.

**Comment by Ebola16** [comment]
No, character .pcs files use LZ77 compression.
I think this script should apply to all file extensions (except .original.pac) to maximize saved space (assuming that ExtendedLZ77 won't cause any compatibility issues).

**Comment by libertyernie** [comment]
Instead of .original.pac, would it be ok to use .pac.original-lz77? Putting that part at the end would make writing the plugin easier.

**Comment by Ebola16** [comment]
Yes, that naming scheme is fine.

**Comment by libertyernie** [comment]
How's this look?

	from BrawlBox.API import bboxapi
	from BrawlLib.SSBB.ResourceNodes import *

	import os
	import shutil

	dir = bboxapi.OpenFolderDialog()
	if dir is not "":
		include_subfolders = bboxapi.ShowYesNoPrompt("Include subfolders?", "Batch conversion")

		ignore_ext = ".original-lz77"

		for root, dirs, files in os.walk(dir):
			for file in files:
				if not file.lower().endswith(ignore_ext):
					node = NodeFactory.FromFile(None, os.path.join(root, file))
					if node.Compression == "LZ77":
						try:
							shutil.copyfile(os.path.join(root, file), os.path.join(root, file + ignore_ext))
							node.Dispose()

							node = NodeFactory.FromFile(None, os.path.join(root, file + ignore_ext));
							node.Compression = "ExtendedLZ77"
							node.Export(os.path.join(root, file))
							node.Dispose()
						except:
							bboxapi.ShowMessage("Cannot export " + file, "Error")
			if not include_subfolders:
				break

**Comment by Ebola16** [comment]
Unfortunately the plugin ran into a MissingMemberException.
Additional information: 'NoneType' object has no attribute 'Compression'

I tried to use my entire SD "private" folder with this plugin.
The error prevented any files from being modified by the plugin.
Let me know if I can provide more information.

![error](https://cloud.githubusercontent.com/assets/17330088/23690182/a258bed6-038d-11e7-9a58-74c58321b023.PNG)

**Comment by Sammi-Husky** [comment]
You said you ran it on the whole private folder? Some of the files in private (such as replays, screenshots, stage builder files including smash stack) cannot be opened or compressed by BBox or Brawllib so that could be a cause. Run it on just the PF folder instead and see if that works.

If that also fails it's probably that it's trying to compress an entry type that can't be compressed or something

**Comment by Ebola16** [comment]
Ideally the plugin would skip files that cannot be opened or compressed by Brawlbox. Users often put non-Brawlbox compatible files in their pf folder (such as Brawlex .dat files or documentation files). An alternative method would be to only make the plugin target .pac and .pcs files but there may come a time when compression can be applied to other files by Brawlbox.

**Comment by Sammi-Husky** [comment]
This will probably fix the problem to be honest.

	```
from BrawlBox.API import bboxapi
	from BrawlLib.SSBB.ResourceNodes import *

	import os
	import shutil

	dir = bboxapi.OpenFolderDialog()
	if dir is not "":
		include_subfolders = bboxapi.ShowYesNoPrompt("Include subfolders?", "Batch conversion")

		ignore_ext = ".original-lz77"

		for root, dirs, files in os.walk(dir):
			for file in files:
				if not file.lower().endswith(ignore_ext):
					node = NodeFactory.FromFile(None, os.path.join(root, file))
					if node  is None:
                                            continue
                                         if node.Compression == "LZ77":
						try:
							shutil.copyfile(os.path.join(root, file), os.path.join(root, file + ignore_ext))
							node.Dispose()

							node = NodeFactory.FromFile(None, os.path.join(root, file + ignore_ext));
							node.Compression = "ExtendedLZ77"
							node.Export(os.path.join(root, file))
							node.Dispose()
						except:
							bboxapi.ShowMessage("Cannot export " + file, "Error")
			if not include_subfolders:
				break
```

**Comment by Sammi-Husky** [comment]
Try this for the plugin and tell me if the problem persists:

```
from BrawlBox.API import bboxapi
from BrawlLib.SSBB.ResourceNodes import *

import os
import shutil

dir = bboxapi.OpenFolderDialog()
if dir is not "":
	include_subfolders = bboxapi.ShowYesNoPrompt("Include subfolders?", "Batch conversion")

	ignore_ext = ".original-lz77"

	for root, dirs, files in os.walk(dir):
		for file in files:
			if not file.lower().endswith(ignore_ext):
				node = NodeFactory.FromFile(None, os.path.join(root, file))
				if node is None
					continue
					
				if node.Compression == "LZ77":
					try:
						shutil.copyfile(os.path.join(root, file), os.path.join(root, file + ignore_ext))
						node.Dispose()

						node = NodeFactory.FromFile(None, os.path.join(root, file + ignore_ext));
						node.Compression = "ExtendedLZ77"
						node.Export(os.path.join(root, file))
						node.Dispose()
					except:
						bboxapi.ShowMessage("Cannot export " + file, "Error")
		if not include_subfolders:
			break
```

**Comment by Ebola16** [comment]
A colon is needed after "if node is None"

Also, this script does not change LZ77 to ExtendedLZ77 for archives that are not the root node. Brawl stages have ARC entries within ARC entries that can benefit from ExtendedLZ77 compression (tested on real Wii with no noticeable problems). An example ARC entry from a stage that is ignored by this script:

![stage](https://cloud.githubusercontent.com/assets/17330088/23740467/af6a1374-0471-11e7-978a-f0482bde09e3.PNG)

**Comment by libertyernie** [comment]
How about this?

	from BrawlBox.API import bboxapi
	from BrawlLib.SSBB.ResourceNodes import *

	import os
	import shutil

	def haslz77(node):
		if node.Compression == "LZ77":
			return True
		for child in node.Children:
			if haslz77(child):
				return True
		return False

	def modifylz77(node):
		if node.Compression == "LZ77":
			node.Compression = "ExtendedLZ77"
		for child in node.Children:
			modifylz77(child)
		return

	dir = bboxapi.OpenFolderDialog()
	if dir is not "":
		include_subfolders = bboxapi.ShowYesNoPrompt("Include subfolders?", "Batch conversion")

		ignore_ext = ".original-lz77"

		for root, dirs, files in os.walk(dir):
			for file in files:
				if not file.lower().endswith(ignore_ext):
					node = NodeFactory.FromFile(None, os.path.join(root, file))
					if node is None:
						continue

					if haslz77(node):
						try:
							shutil.copyfile(os.path.join(root, file), os.path.join(root, file + ignore_ext))
							node.Dispose()

							node = NodeFactory.FromFile(None, os.path.join(root, file + ignore_ext));
							modifylz77(node)
							node.Export(os.path.join(root, file))
							node.Dispose()
						except:
							bboxapi.ShowMessage("Cannot export " + file, "Error")
			if not include_subfolders:
				break

**Comment by Ebola16** [comment]
Unfortunately the plugin ran into a NullReferenceException.
Additional information: 'Object reference not set to an instance of an object'

I tried to use my entire SD "private" folder with this plugin.
The error prevented any files from being modified by the plugin.
Let me know if I can provide more information.

![capture2](https://cloud.githubusercontent.com/assets/17330088/23963517/e3686c32-0987-11e7-8375-c2478464ae08.PNG)

**Comment by libertyernie** [comment]
Maybe this will help. This will only look in child nodes for LZ77 compression if the parent is an ARCNode, so it doesn't go down all the way.

	from BrawlBox.API import bboxapi
	from BrawlLib.SSBB.ResourceNodes import *

	import os
	import shutil

	def haslz77(node):
		if node.Compression == "LZ77":
			return True
		if node.GetType().Name == "ARCNode":
			for child in node.Children:
				if haslz77(child):
					return True
		return False

	def modifylz77(node):
		if node.Compression == "LZ77":
			node.Compression = "ExtendedLZ77"
		if node.GetType().Name == "ARCNode":
			for child in node.Children:
				modifylz77(child)
		return

	dir = bboxapi.OpenFolderDialog()
	if dir is not "":
		include_subfolders = bboxapi.ShowYesNoPrompt("Include subfolders?", "Batch conversion")

		ignore_ext = ".original-lz77"

		for root, dirs, files in os.walk(dir):
			for file in files:
				if not file.lower().endswith(ignore_ext):
					try:
						node = NodeFactory.FromFile(None, os.path.join(root, file))
						if node is None:
							continue

						if haslz77(node):
							shutil.copyfile(os.path.join(root, file), os.path.join(root, file + ignore_ext))
							node.Dispose()

							node = NodeFactory.FromFile(None, os.path.join(root, file + ignore_ext));
							modifylz77(node)
							node.Export(os.path.join(root, file))
							node.Dispose()
					except:
						bboxapi.ShowMessage("Cannot export " + file, "Error")
			if not include_subfolders:
				break

**Comment by Ebola16** [comment]
The latest version seems to do the trick! Thank you libertyernie and Sammi-Husky for your help! This can be useful for saving space on Dolphin where SDHC emulation isn't an option yet.
