### ISSUE TITLE
NRE when attempting to open .rel constructor, destructor, or unresolved functions

### ISSUE THREAD

**Issue by Ebola16** [libertyernie/brawltools#107]
Tested with Brawlbox v0.78 rc1 and the .rel files in common2_en.pac and common3_en.pac

**Comment by libertyernie** [comment]
Which .rel file did you use?

**Comment by Ebola16** [comment]
Common3's sora_menu_sel_char will definitely reproduce this problem.

**Comment by libertyernie** [comment]
Found the problem - it'll be fixed in 0.78 final.
