### ISSUE TITLE
Brawlbox Advanced Model Editor Screenshots are black

### ISSUE THREAD

**Issue by Ebola16** [libertyernie/brawltools#117]
Steps to reproduce:
1. Import any model into Brawlbox
2. Preview the model in the Advanced Model Editor
3. Take a screenshot via the options menu (with or without transparent background)
4. Observe black PNG. Visual Studio debug did not complain when exporting the black PNG.

Win 10 Pro x64
Intel Core i7-4702MQ CPU @2.20GHz
GeForce GT 750M
2x 8GB Hynix 1600MHz
GeForce Game Ready Driver 381.89

**Comment by libertyernie** [comment]
It uses OpenTK to grab the screenshot (line 570 of ModelPanel.cs). It works on my laptop so I don't think I can help debug it.

**Comment by AtlasOmegaAlpha** [comment]
It happens to me also, sometimes. However, after a second try, it works.

**Comment by BlackJax96** [comment]
This is a known bug, I'm just not really sure how to go about fixing it. [I've pushed a minor change you can test.](https://github.com/libertyernie/brawltools/commit/fe4838dd30dd7278fcd51fe406e45bc27b39808f)

**Comment by Ebola16** [comment]
This does appear to fix the problem for me. Closing, but I can reopen if @AtlasOmegaAlpha is still able to reproduce it.
