### ISSUE TITLE
Shader corruption

### ISSUE THREAD

**Issue by AtlasOmegaAlpha** [libertyernie/brawltools#120]
When you edit any value from the stages of a shader with more than one shader with BrawlBox, it corrupts the shader indexes:
![image](https://cloud.githubusercontent.com/assets/26127273/26447029/efc63698-4146-11e7-8171-2ccfccb24b9d.png) You can see how the second index is changed to 61 12, and that makes the object with that shader look weird in game in a retail Wii. However, this shows correctly on Dolphin. Changing 61 12 with 61 11 in hex and reimporting the shader fixes this issue.

**Comment by libertyernie** [comment]
public void SetStage(int index) 
    {
        if (index % 2 == 0) //Even
        {
            eClrEnv.Mem = (BPMemory)((int)BPMemory.BPMEM_TEV_COLOR_ENV_0 + index * 2);
            eAlpEnv.Mem = (BPMemory)((int)BPMemory.BPMEM_TEV_ALPHA_ENV_0 + index * 2);
            eCMD.Mem = (BPMemory)((int)BPMemory.BPMEM_IND_CMD0 + index * 2);  
        }
        else //Odd
        {
            oClrEnv.Reg = 
            oAlpEnv.Reg = 
            oCMD.Reg = 0x61;

            oClrEnv.Mem = (BPMemory)((int)BPMemory.BPMEM_TEV_COLOR_ENV_0 + index * 2);
            oAlpEnv.Mem = (BPMemory)((int)BPMemory.BPMEM_TEV_ALPHA_ENV_0 + index * 2);
            oCMD.Mem = (BPMemory)((int)BPMemory.BPMEM_IND_CMD0 + index * 2);  
        }
    }

Here's the code where it sets those indexes. BPMemory.BPMEM_IND_CMD0 is 0x10, so adding index * 2 makes the next ones 0x12, 0x14 when it looks like they ought to be 0x11, 0x12, ...

I'm not sure about the others. BPMEM_TEV_COLOR_ENV_0 is 0xC0 and BPMEM_TEV_ALPHA_ENV_0 is 0xC1. I'm guessing those should stay as is?

**Comment by AtlasOmegaAlpha** [comment]
This problem only occurred to me with materials that use 2 different texture UVs, 1 map for each, and specifically, for shadow mapping. The only difference between the original file (a course model made by Nintendo) and the exported shader, edited by BrawlBox, is that specific value, and indeed, changing that value to 0x12 fixes the issue.

Here is a preview in HEX of the original file used in a Nintendo's course:
![image](https://cloud.githubusercontent.com/assets/26127273/26533628/0cbe1fae-441c-11e7-8808-bb20d7c8c184.png)

And here is the same, being edited a value and editing it back to its original value and exported by BrawlBox:
![image](https://cloud.githubusercontent.com/assets/26127273/26533645/40722ec6-441c-11e7-85e9-708bbbfc0018.png)

In game, the shader edited by BrawlBox makes the road look like if the TexMap0 doesn't exist: only the shadow map is visible.

**Comment by AtlasOmegaAlpha** [comment]
I've just tried with the new code you put to try to solve this, and now it writes 61 00 instead of 61 11.

**Comment by BlackJax96** [comment]
Dang. Try the next fix I just pushed

**Comment by AtlasOmegaAlpha** [comment]
It works fine now.
