### ISSUE TITLE
Shader compilation issue

### ISSUE THREAD

**Issue by Ebola16** [libertyernie/brawltools#121]
After solving #83, it has become apparent that the model below has shader compilation issues when previewed in the Advanced Model Editor but not when selecting the MDL0. Is the problem here malformed shaders? Regardless, the differences between selecting the MDL0 and the Advanced Model Editor make this worth opening an issue. It should also be known that Dolphin and a real Wii display models from this mod, and its recolors, slightly differently (https://bugs.dolphin-emu.org/issues/9268)

[FitLloyd00.zip](https://github.com/libertyernie/brawltools/files/543347/FitLloyd00.zip)

![l](https://cloud.githubusercontent.com/assets/17330088/26568818/7f7a6652-44d4-11e7-8915-8a7626d203de.PNG)

Visual studio's debug output:

ERROR: 0:53: 'texture0' : undeclared identifier 
ERROR: 0:53: 'texture2D' : no matching overloaded function found (using implicit conversion) 
ERROR: 0:53: 'rgba' : field selection requires structure, vector, or matrix on left hand side 
ERROR: 0:53: 'assign' :  cannot convert from 'const float' to '4-component vector of float'

001: //MDL0 fragment shader generated by BrawlLib
002: //lambert2
003: 
004: #version 120
005: 
006: float satlf(float f)
007: {
008: 	return (f < 0.0) ? 0.0 : f;
009: }
010: 
011: vec3 satlv(vec3 v)
012: {
013: 	return vec3(satlf(v.x),satlf(v.y),satlf(v.z));
014: }
015: 
016: float satf(float f)
017: {
018: 	return clamp(f, 0.0, 1.0);
019: }
020: 
021: vec3 satv(vec3 v)
022: {
023: 	return clamp(v, vec3(0.0), vec3(1.0));
024: }
025: 
026: 
027: uniform vec4 creg[3];
028: uniform vec4 ccreg[4];
029: 
030: uniform int scnFogType;
031: uniform float scnFogStartZ;
032: uniform float scnFogEndZ;
033: uniform vec3 scnFogColor;
034: 
035: varying vec3 vPosition;
036: varying vec3 vNormal;
037: varying vec4 vtxColor0;
038: varying vec4 vtxColor1;
039: varying vec4 lightChannel0;
040: varying vec4 lightChannel1;
041: 
042: void main()
043: {
044: 	vec4 rPrev = vec4(1.0);
045: 	vec4 r2 = creg[2];
046: 	vec4 texColor;
047: 	vec4 rasColor;
048: 	vec4 constColor;
049: 	
050: 	
051: 	//Shader0 Stage0
052: 	{
053: 		texColor = texture2D(texture0, gl_TexCoord[0].st).rgba;
054: 		rasColor = lightChannel0.rgba;
055: 		
056: 		//Color Operation
057: 		rPrev.rgb = (vec3(0.0) + (mix(vec3(0.0),texColor.rgb,rasColor.rgb))) * 4.0;
058: 		rPrev.rgb = satv(rPrev.rgb);
059: 		
060: 		//Alpha Operation
061: 		rPrev.a = (0.0 + (mix(0.0,texColor.a,rasColor.a)));
062: 		rPrev.a = satf(rPrev.a);
063: 	}
064: 	
065: 	
066: 	//Shader0 Stage1
067: 	{
068: 		constColor.rgb = ccreg[1].rgb;
069: 		rasColor = lightChannel0.rgba;
070: 		
071: 		//Color Operation
072: 		rPrev.rgb = (rPrev.rgb + (mix(vec3(0.0),constColor.rgb,rasColor.rgb)));
073: 		rPrev.rgb = satv(rPrev.rgb);
074: 		
075: 		//Alpha Operation
076: 		rPrev.a = (0.0 + (mix(rPrev.a,0.0,0.0)));
077: 		rPrev.a = satf(rPrev.a);
078: 	}
079: 	
080: 	
081: 	//Shader0 Stage2
082: 	{
083: 		constColor.rgb = ccreg[0].rgb;
084: 		
085: 		//Color Operation
086: 		rPrev.rgb = (vec3(0.0) + (mix(rPrev.rgb,r2.rgb,constColor.rgb)));
087: 		rPrev.rgb = satv(rPrev.rgb);
088: 		
089: 		//Alpha Operation
090: 		rPrev.a = (0.0 + (mix(rPrev.a,0.0,0.0)));
091: 		rPrev.a = satf(rPrev.a);
092: 	}
093: 	
094: 	
095: 	//SCN0 Fog
096: 	if (scnFogType != 0)
097: 	{
098: 		float fogDensity = 0.0;
099: 		float posZ = length(vPosition);
100: 		if (posZ <= scnFogStartZ)
101: 		{
102: 			fogDensity = 0.0;
103: 		}
104: 		else if (posZ >= scnFogEndZ)
105: 		{
106: 			fogDensity = 1.0;
107: 		}
108: 		else if ((scnFogType == 2) || (scnFogType == 10))
109: 		{
110: 			//Linear
111: 			fogDensity = (posZ - scnFogStartZ) / (scnFogEndZ - scnFogStartZ);
112: 		}
113: 		else if ((scnFogType == 4) || (scnFogType == 12))
114: 		{
115: 			//Exp
116: 			fogDensity = 1.0 - exp2(-8.0 * ((posZ - scnFogStartZ) / (scnFogEndZ - scnFogStartZ)));
117: 		}
118: 		else if ((scnFogType == 5) || (scnFogType == 13))
119: 		{
120: 			//Exp^2
121: 			fogDensity = 1.0 - exp2(-8.0 * pow((posZ - scnFogStartZ) / (scnFogEndZ - scnFogStartZ), 2.0));
122: 		}
123: 		else if ((scnFogType == 6) || (scnFogType == 14))
124: 		{
125: 			//RevExp
126: 			fogDensity = exp2(-8.0 * ((scnFogEndZ - posZ) / (scnFogEndZ - scnFogStartZ)));
127: 		}
128: 		else if ((scnFogType == 7) || (scnFogType == 15))
129: 		{
130: 			//RevExp^2
131: 			fogDensity = exp2(-8.0 * pow((scnFogEndZ - posZ) / (scnFogEndZ - scnFogStartZ), 2.0));
132: 		}
133: 		rPrev.rgb = mix(rPrev.rgb, scnFogColor, satf(fogDensity));
134: 	}
135: 	gl_FragColor = rPrev;
136: 	gl_FragColor.a = 1.0;
137: }
138: 

Attached fragment shader is not compiled.

'BrawlBox.exe' (CLR v4.0.30319: BrawlBox.exe): Loaded 'Microsoft.GeneratedCode'. 
The thread 0x1560 has exited with code 0 (0x0).
The thread 0x2390 has exited with code 0 (0x0).
ERROR: 0:53: 'texture0' : undeclared identifier 
ERROR: 0:53: 'texture2D' : no matching overloaded function found (using implicit conversion) 
ERROR: 0:53: 'rgba' : field selection requires structure, vector, or matrix on left hand side 
ERROR: 0:53: 'assign' :  cannot convert from 'const float' to '4-component vector of float'

001: //MDL0 fragment shader generated by BrawlLib
002: //lambert2
003: 
004: #version 120
005: 
006: float satlf(float f)
007: {
008: 	return (f < 0.0) ? 0.0 : f;
009: }
010: 
011: vec3 satlv(vec3 v)
012: {
013: 	return vec3(satlf(v.x),satlf(v.y),satlf(v.z));
014: }
015: 
016: float satf(float f)
017: {
018: 	return clamp(f, 0.0, 1.0);
019: }
020: 
021: vec3 satv(vec3 v)
022: {
023: 	return clamp(v, vec3(0.0), vec3(1.0));
024: }
025: 
026: 
027: uniform vec4 creg[3];
028: uniform vec4 ccreg[4];
029: 
030: uniform int scnFogType;
031: uniform float scnFogStartZ;
032: uniform float scnFogEndZ;
033: uniform vec3 scnFogColor;
034: 
035: varying vec3 vPosition;
036: varying vec3 vNormal;
037: varying vec4 vtxColor0;
038: varying vec4 vtxColor1;
039: varying vec4 lightChannel0;
040: varying vec4 lightChannel1;
041: 
042: void main()
043: {
044: 	vec4 rPrev = vec4(1.0);
045: 	vec4 r2 = creg[2];
046: 	vec4 texColor;
047: 	vec4 rasColor;
048: 	vec4 constColor;
049: 	
050: 	
051: 	//Shader0 Stage0
052: 	{
053: 		texColor = texture2D(texture0, gl_TexCoord[0].st).rgba;
054: 		rasColor = lightChannel0.rgba;
055: 		
056: 		//Color Operation
057: 		rPrev.rgb = (vec3(0.0) + (mix(vec3(0.0),texColor.rgb,rasColor.rgb))) * 4.0;
058: 		rPrev.rgb = satv(rPrev.rgb);
059: 		
060: 		//Alpha Operation
061: 		rPrev.a = (0.0 + (mix(0.0,texColor.a,rasColor.a)));
062: 		rPrev.a = satf(rPrev.a);
063: 	}
064: 	
065: 	
066: 	//Shader0 Stage1
067: 	{
068: 		constColor.rgb = ccreg[1].rgb;
069: 		rasColor = lightChannel0.rgba;
070: 		
071: 		//Color Operation
072: 		rPrev.rgb = (rPrev.rgb + (mix(vec3(0.0),constColor.rgb,rasColor.rgb)));
073: 		rPrev.rgb = satv(rPrev.rgb);
074: 		
075: 		//Alpha Operation
076: 		rPrev.a = (0.0 + (mix(rPrev.a,0.0,0.0)));
077: 		rPrev.a = satf(rPrev.a);
078: 	}
079: 	
080: 	
081: 	//Shader0 Stage2
082: 	{
083: 		constColor.rgb = ccreg[0].rgb;
084: 		
085: 		//Color Operation
086: 		rPrev.rgb = (vec3(0.0) + (mix(rPrev.rgb,r2.rgb,constColor.rgb)));
087: 		rPrev.rgb = satv(rPrev.rgb);
088: 		
089: 		//Alpha Operation
090: 		rPrev.a = (0.0 + (mix(rPrev.a,0.0,0.0)));
091: 		rPrev.a = satf(rPrev.a);
092: 	}
093: 	
094: 	
095: 	//SCN0 Fog
096: 	if (scnFogType != 0)
097: 	{
098: 		float fogDensity = 0.0;
099: 		float posZ = length(vPosition);
100: 		if (posZ <= scnFogStartZ)
101: 		{
102: 			fogDensity = 0.0;
103: 		}
104: 		else if (posZ >= scnFogEndZ)
105: 		{
106: 			fogDensity = 1.0;
107: 		}
108: 		else if ((scnFogType == 2) || (scnFogType == 10))
109: 		{
110: 			//Linear
111: 			fogDensity = (posZ - scnFogStartZ) / (scnFogEndZ - scnFogStartZ);
112: 		}
113: 		else if ((scnFogType == 4) || (scnFogType == 12))
114: 		{
115: 			//Exp
116: 			fogDensity = 1.0 - exp2(-8.0 * ((posZ - scnFogStartZ) / (scnFogEndZ - scnFogStartZ)));
117: 		}
118: 		else if ((scnFogType == 5) || (scnFogType == 13))
119: 		{
120: 			//Exp^2
121: 			fogDensity = 1.0 - exp2(-8.0 * pow((posZ - scnFogStartZ) / (scnFogEndZ - scnFogStartZ), 2.0));
122: 		}
123: 		else if ((scnFogType == 6) || (scnFogType == 14))
124: 		{
125: 			//RevExp
126: 			fogDensity = exp2(-8.0 * ((scnFogEndZ - posZ) / (scnFogEndZ - scnFogStartZ)));
127: 		}
128: 		else if ((scnFogType == 7) || (scnFogType == 15))
129: 		{
130: 			//RevExp^2
131: 			fogDensity = exp2(-8.0 * pow((scnFogEndZ - posZ) / (scnFogEndZ - scnFogStartZ), 2.0));
132: 		}
133: 		rPrev.rgb = mix(rPrev.rgb, scnFogColor, satf(fogDensity));
134: 	}
135: 	gl_FragColor = rPrev;
136: 	gl_FragColor.a = 1.0;
137: }
138: 

Attached fragment shader is not compiled.

The program '[21420] BrawlBox.exe' has exited with code 0 (0x0).

**Comment by BlackJax96** [comment]
This is a custom model import, yeah? Because there are a number of problems with the way the model was set up. Each medium is handling the problems in their own way because it's not supposed to be set up like that in the first place.

The first obvious problem is the model is version 8, but Brawl models are all version 9.

Second, the objects that appear black/too bright have **no color node**, but their materials expect color data **per vertex** (you can fix this by getting rid of the color node completely and setting the materials to read from the constant raster color).

The reason the shader isn't compiling there is because the one shader you have ALL the materials using **EXPECTS** at least one texture, in slot 0. But lambert2 has no textures, so the generated shader code is flawed! This also means that any materials using more than one texture are not living up to their potential. Also, not to mention lambert2 is used by two objects which are literally just two triangles and don't represent anything. They're useless.

Third, some of your textures are version 3, but Brawl uses version 1. This probably doesn't affect anything but you should change it to be safe.

I can implement code to work around and warn the user about errors like this, but it won't fix the fact that your model itself is flawed. To show the fixes I'm explaining, [I implemented them in your model myself.](https://www.dropbox.com/s/ihbkshbdckd1uof/FitWolf00.pcs?dl=0) Go ahead and test that.

**Comment by Ebola16** [comment]
Thank you for your thorough explanation and example. This is a custom model that I downloaded which had shader and material setting combinations that I haven't seen before. I was under the impression that the author of the mod was trying to do something complicated and I wanted to understand what that was. It now seems like too much is botched on this import and default materials and shaders are better.

If I understand correctly, and after deleting lambert2, all of the corrections you suggested would have been generated by default when creating the MDL0 from the DAE, yes? If so, then your explanations make sense on how differing from those default settings can cause this issue.

Regardless, the shader is malformed and the problem does not lie with Brawlbox so closing.
