### ISSUE TITLE
Brawlbox display quirks

### ISSUE THREAD

**Issue by Ebola16** [libertyernie/brawltools#128]
[FitDrDark.zip](https://github.com/libertyernie/brawltools/files/1063019/FitDrDark.zip)

- [X] Bones can remain highlighted after selected in certain circumstances (starting with one initial bone selection).
- [X] Bones can remain highlighted after selected in certain circumstances (starting with multiple initial bone selections).

~~Brawlbox data tables now have dark gray along the edges and seemingly inappropriately colored fields. I don't know if this change was intentional though.~~
(Won't Fix, see https://stackoverflow.com/questions/43609548/windows-10-creators-update-changes-the-style-of-propertygrid-control)

Steps to reproduce the selection highlight glitch:
1. Press Ctrl+Del to delete NewBone4 (BoneIndex 66). Then release Ctrl+Del. ThrowN will now be highlighted.
2. Press Up to select the bone above ThrowN.
3. Both bones will be highlighted (even thow ThrowN should no longer be highlighted).

I am fairly confident that the ~~gray data table values~~ and selection highlighting issues didn't happen until the Windows 10 Creators Update.

![2017-06-09 1 copy](https://user-images.githubusercontent.com/17330088/26961753-30f36744-4caf-11e7-8451-a5903bfb9d60.png)

**Comment by libertyernie** [comment]
The bone selection bug is due to a new feature introduced recently where you can select multiple bones. It happens pre-Creators Update too. I'm not sure how to go about fixing it at the moment.

**Comment by Ebola16** [comment]
Ah, the bone selection bug's timing was a coincidence then.

Also, in reference to the gray shaded table bug, it wouldn't look so bad if the first field under an expected gray box location wasn't also gray (see "VisibilityDrawCalls" in the original post or "ScalingRule" below)

![capture2](https://user-images.githubusercontent.com/17330088/26992351-4296aede-4d2c-11e7-8a5d-9e969d50e863.PNG)

**Comment by Ebola16** [comment]
I wish Github would give us notification whenever a commit is added that references an issue that I create...

954bc0e fixed the selection problem when one bone was originally selected but the same issue occurs if multiple bones are originally selected. For example:
1. Select both NewBone4 then NewBone3 (BoneIndex 66 and 65)
2. Press UP to select NewBone2
3. Observe that all three bones are highlighted. Only NewBone2 should be highlighted.

![2017-06-14](https://user-images.githubusercontent.com/17330088/27115965-28badec2-509c-11e7-8343-a73497dcf31f.png)

**Comment by libertyernie** [comment]
This commit should clear the multi-selection when you press up/down, so just one is selected. (It takes the one above/below the most recently selected node, which you can tell from the dotted line around it.)

**Comment by Ebola16** [comment]
Yes, that appeared to solve the problem. Only the inappropriately colored fields remain for this issue.

**Comment by libertyernie** [comment]
I think the edges and the first field are going to be the same color no matter what I do, while the field is inactive. If it has focus, the field turns blue.

I can change the gray to any other color, though. The issue is this one: https://stackoverflow.com/questions/43609548/windows-10-creators-update-changes-the-style-of-propertygrid-control

**Comment by Ebola16** [comment]
Haha well at least I wasn't completely off when these issues appeared around the time of Win 10 Creators Update...

I realized that this has always been how Brawlbox worked, Win 10 Creators Update just changed the color scheme and made it more prominent. Although the inactive selection does look awkward, the darker title fields do help separate blocks of data.

Ideally, the edges and an inactive selection should be different colors but changing that seems like too much trouble. I'm fine with interpreting that as Won't Fix.
