### ISSUE TITLE
BrawlBox v0.78's progress bar is jumpy when playing BRSTMs

### ISSUE THREAD

**Issue by JoFelix2** [libertyernie/brawltools#137]
The timer goes up way too slowly, then jumps to the correct value every so often.
Same thing with the progress bar.
This is just a visual glitch; audio playback is not affected.
This was not an issue in BrawlBox v0.77.

**Comment by libertyernie** [comment]
Perhaps this has something to do with OpenAL. BrawlBox will use OpenAL if it can, and fall back to DirectSound if it can't (and it's running on Windows.)

Right now there's no setting to turn off OpenAL or tell if you're using it, but I'd like to add one.

**Comment by JoFelix2** [comment]
(I gotta work on my spam filters.)
Yes, this also happens in the BRSTM creation window.
Also I've noticed when I open BrawlBox by double-clicking an existing BRSTM and then want to create a new BRSTM, the creation window plays the audio way too fast. When I cancel out of the creation, the original window doesn't play the audio at all.
(Also, is it normal that the resultin loop points aren't exactly the ones you type in? I have no idea how BRSTMs actually work.)

**Comment by libertyernie** [comment]
@JoFelix2 The loop point has to be a multiple of 14336, so it will add the same amount to both start and end points to make it work.

I bet OpenAL is the problem. In the next version I'll make it prefer DirectSound when available.

**Comment by JoFelix2** [comment]
Why do the loop points have to be multiples of 14336, and what happens if I edit them in a hex editor?
(Also yay my spam filters work now.)

**Comment by libertyernie** [comment]
14336 is the block size. I don't know what happens if you edit it with a hex editor - maybe the Wii won't play it properly?

**Comment by libertyernie** [comment]
Try the BrawlBox.exe in this zip file. It's just like 0.78 hotfix 1, except it uses DirectSound instead of OpenAL if it can. You'll need the other files (.dll, etc) from 0.78 hotfix 1.
[BrawlBox.zip](https://github.com/libertyernie/brawltools/files/1185287/BrawlBox.zip)

**Comment by JoFelix2** [comment]
It's still jumpy both in the original window and in the BRSTM creation window. The creation window still plays it way too fast when I create a new BRSTM "on top of" an existing one. The only thing that's changed is that when I run BrawlBox directly (aka not by double-clicking an existing BRSTM), Windows SmartScreen tells me it doesn't trust the app.

**Comment by libertyernie** [comment]
Oh, it just occurred to me that the file I needed to give you was
brawllib.all, not brawlbox.exe. Ill do that later today.

**Comment by libertyernie** [comment]
[BrawlLib.zip](https://github.com/libertyernie/brawltools/files/1185871/BrawlLib.zip)
Here's the BrawlLib.dll file. It goes in the lib folder.

**Comment by JoFelix2** [comment]
Thanks, it works like a charm!
(Also I re-replaced the .exe so SmartScreen doesn't bug me.)
Although this got me wondering ... "Octoling Rendezvous (Battle Beat)" has a loop start point of 200704, which is a multiple of 14336, and a loop end point of 2216705, which is not a multiple of 14336.
