### ISSUE TITLE
Expanded fields should remain expanded when looking at a different entry

### ISSUE THREAD

**Issue by Ebola16** [libertyernie/brawltools#145]
I'm not sure the best way to describe this problem so I'll give an example using default Final Destination:

1. Expand ModelData[1] -> StgFinal00space -> Materials
2. Expand amanogawa2's LightChannel0 field
![2017-08-13 1](https://user-images.githubusercontent.com/17330088/29253663-5e4001f0-8051-11e7-9df0-ae7308f59887.png)
3. Select black1 material
4. Observe that LightChannel0 has collapsed

This can be very annoying if you want to compare LightChannel values between two materials.

**Comment by libertyernie** [comment]
I wonder if there's any reason _not_ to have everything expanded after you select a node. Adding propertyGrid1.ExpandAllGridItems() right after the selected object is changed would do that.

**Comment by Ebola16** [comment]
I can't think of any. I assume LightChannel# is only collapsed in the first place since they contain a lot of fields.
