### ISSUE TITLE
EditAllDialog: Transformations are applied to all planes

### ISSUE THREAD

**Issue by Ebola16** [libertyernie/brawltools#171]
Follow up to #90 

![capture11](https://cloud.githubusercontent.com/assets/17330088/20509613/de409120-b037-11e6-854b-4ae17d68bf59.PNG)

"Replace", "Multiply", and "Divide" will apply a transformation to all planes (x,y,z). Since users can switch between addition and multiplication, a single default value is problematic.

Perhaps planes should have their default values set to N (null), which would not apply a transformation to the animations? This allows a user to be able to multiply one plane without worrying about the others. It will also prevent users from accidentally multiplying by 0 or adding 1 if they aren't careful about which operation they're using.

A small text box should also be added explaining what N means.

**Comment by libertyernie** [comment]
Could we just use the word "null" instead of the letter N? Or maybe an empty string would be better.

**Comment by Ebola16** [comment]
Oh yeah, I like the empty string idea.

**Comment by libertyernie** [comment]
This seems to be working for me.

**Comment by Ebola16** [comment]
LGTM. Thanks!
