### ISSUE TITLE
Crash1 Collision Type

### ISSUE THREAD

**Issue by soopercool101** [libertyernie/brawltools#174]
The collision type currently labelled as "Crash1" has been found to be used as a Spikes Hazard collision on Target Test and Target Test based stages. As such, I propose that the collision names be updated to the following:
Crash1->SpikesTargetTest
(Or something similar, as it should be noted that the collision does crash on non Target Test based stages)

Crash2->Crash1
Crash3->Crash2
(Or they could stay the same. This doesn't matter so much)

**Comment by libertyernie** [comment]
Renamed Crash1 to SpikesTargetTestOnly in commit 1b9e2324a5fc9d2eca2cbbaf04a79732c1939bbf.

I think it's best to keep Crash2 and Crash3 as is, so we don't reuse names for one type that used to refer to another.
