### ISSUE TITLE
Implementing BrawlLib into another project

### ISSUE THREAD

**Issue by The-Silver-Kid** [libertyernie/brawltools#177]
I am creating a program to read and play RSTM files (Mostly BRSTM and BCSTM files) and I was wondering how I would go about using BrawlLib to handle this for me so I wouldnt have to recreate one myself.
I have looked at the RSTMNode.cs and all of its base classes but I just cant seem to get anywhere with it.

Also if this is not the correct place for this type of a request, sorry. i just didn't know where else to go for it.

**Comment by libertyernie** [comment]
You can create an RSTMNode from a file with NodeFactory:

    NodeFactory.FromFile(null, "C:\\file.brstm");

The important thing to note is that RSTMNode (and a couple other classes, I think) implement IAudioSource. Calling CreateStreams() will get you an array of IAudioStream (usually just one) which are either mono or stereo. Then you can use ReadSamples (and Wrap when you reach the end of the loop, if any.)

You might want to check out [VGAudio](https://github.com/Thealexbarney/VGAudio) - it supports RSTM and a bunch of other formats, and it's also written in C#.

**Comment by The-Silver-Kid** [comment]
Thanks.
Ill look into both and see what works best for what I need.
