### ISSUE TITLE
Port to .NET Core and other platforms

### ISSUE THREAD

**Issue by Exagone313** [libertyernie/brawltools#181]
Hi,

I'm actually using BrawlBox via Wine on GNU/Linux and it works fine (not many glitches), but it would be nice if it could be native. I have no knowledge in C# and .NET Framework and I'm told there are differences with .NET Core (for example, the minimum target version, 4.6.2 rather than 4.0.0). Also, I don't know if .NET Core has all needed features (I'm [not even sure](https://stackoverflow.com/questions/38169500/how-can-i-develop-cross-platform-gui-application-using-net-core) if it supports GUI...).
I see also that it has a part in Python, what about it?

Do you have any thought? Thanks!

**Comment by libertyernie** [comment]
.NET Core is going to get Windows Forms support in version 3, but only on Windows (https://blogs.msdn.microsoft.com/dotnet/2018/05/07/net-core-3-and-support-for-windows-desktop-applications/) so there's not much reason to use it.

It does mostly work on Mono, though. You should use the 32-bit version of Mono if you can - not all of BrawlBox is built to work with 64-bit pointers. Mono's implementation of Windows Forms is pretty complete but also pretty ugly :)

**Comment by Sammi-Husky** [comment]
If .NET Core ever supports winforms on platforms other than windows we can look into this again, but im going to close the issue for now since the decision is currently a no.

**Comment by libertyernie** [comment]
I'm going to reopen this, since .NET Core 3.0 adds support for WinForms (only on Windows, though)
