### ISSUE TITLE
Pull Request #195 doesn't work properly

### ISSUE THREAD

**Issue by soopercool101** [libertyernie/brawltools#197]
Pull Request #195 (as implemented in commit a2628c56d7ef5cb065981f1bf1ec4054c46b60a2) does not properly refer to actual variables and leads to compiler errors.

**Comment by MichaelHinrichs** [comment]
I forgot about some other file that I changed. I'll try to find it and re-do the pull request with the necessary code.

**Comment by MichaelHinrichs** [comment]
fixed.
[https://github.com/libertyernie/brawltools/pull/198](url)
