### ISSUE TITLE
I Cannot Export Everything from Any Archive

### ISSUE THREAD

**Issue by P0W3** [libertyernie/brawltools#200]
I was exporting everything from any archive (example: U8 archive), but the error occurred.
![1](https://user-images.githubusercontent.com/18279115/47579344-b0e4e200-d919-11e8-9699-5b16e3f65f73.png)

BrawlBox (v0.78) (Hotfix 1)
Windows 10 Home Insider Preview (Windows Version 10.0.15031) (64-bit)

**Comment by libertyernie** [comment]
This looks like a duplicate of #196
