### ISSUE TITLE
Brawlbox on Unix systems

### ISSUE THREAD

**Issue by Overc1ocker** [libertyernie/brawltools#208]
Hi there, I’m trying to use brawlcats on a Linux system with the latest wine-stable, and I get a “application experienced a fatal error and must close.” Please fix if you are interested, if not, thank you anyway :)

**Comment by libertyernie** [comment]
You might have more luck running it with Mono. (It has to be the 32-bit version of Mono, though.)

**Comment by Overc1ocker** [comment]
It fails on both

**Comment by libertyernie** [comment]
Unfortunately, the only way to really do this properly would be to write a new GUI that doesn't use WinForms, and that would be a lot of effort.

Does running it with mono give you an error in the terminal?

**Comment by Overc1ocker** [comment]
Yes
https://pastebin.com/dWFYMvbE

**Comment by libertyernie** [comment]
Looks like the problem shows up when it tries to connect to DirectSound. It would be nice to add a way to turn off BrawlBox's audio output - I'll look into it when I have time.

P.S. Have you tried this?

    $ mono '/home/Mlinux/Downloads/brawlbox/BrawlBox.exe'

**Comment by Overc1ocker** [comment]
Yes. I can’t even open a file with brawlbox in mono.

**Comment by uyjulian** [comment]
Use `winetricks dotnet40` in a separate WINEPREFIX for a quick fix.

**Comment by Overc1ocker** [comment]
Dotnet 40 did it!!
If you want to add this fix to the readme, please do!

**Comment by libertyernie** [comment]
Thanks! I added it to Changelog.txt.
