### ISSUE TITLE
Alleviate some issues with 64 bit builds

### ISSUE THREAD

**Issue by suludas** [libertyernie/brawltools#227]
Though users are instructed to build for x86, the x86 build fails to open/export large archives as seen in #216 and #226.  
An x64 build is able to open and export the problematic pbr_sounds.brsar mentioned in #226 (and possibly the one in #216, though I've not tested it) after a few small changes as in this quick and dirty commit:
https://github.com/suludas/brawltools/commit/62df8bfddf02845d470384a9a5f0297e25d9bcd0

**Comment by libertyernie** [comment]
I might as well merge these changes in, they look good to me.
