### ISSUE TITLE
[Question] Can I steal part of your code?

### ISSUE THREAD

**Issue by marcussacana** [libertyernie/brawltools#229]
I want implement the LZ77 decompressor/compressor to my program (open source & freeware)
But well, Why the hell I will lost time writing a fucking compression algorithm when I can just copy?

So, it's basically this, I don't see any license in the repositorie then I'm asking.

**Comment by libertyernie** [comment]
I'm fine with you taking any code *that I've written* that currently exists in the brawltools repository, under either the MIT License or Apache License 2.0.

That being said, I don't think I wrote the LZ77 code, so you'd have to look at the git history for that code and find out who did, and ask them. Unfortunately when I forked this project there was no license attached to it, and I can't really make any sort of copyright claim about other people's work.

**Comment by marcussacana** [comment]
Okay, thank you, I will do a proper research, because after some tests looks like my game isn't using a default LZ77 algorithm, He have the lz77 signature but I don't found any code that decompressed the data, well, if I need of the code of this tool I will give a look in the git history then, thank you.
