### ISSUE TITLE
Another error

### ISSUE THREAD

**Issue by WeeGee-mc** [libertyernie/brawltools#231]
Help! So I'm new here in brawlbox and so far I've encountered a terrible glitch. While I was making my mario kart wii custom track, I managed to import the model, but when I import the texture, an error happens. Please anyone, help me. I really want to finish this track. 
![Annotation 2020-05-24 032544](https://user-images.githubusercontent.com/58914594/82742377-697d3c80-9d6e-11ea-955d-561d0b0f7858.png)

**Comment by libertyernie** [comment]
What's the file format of the texture file you're trying to import? Could you upload it or post a link?

Also try [BrawlCrate](https://github.com/soopercool101/BrawlCrate) and see if it's fixed there.

**Comment by WeeGee-mc** [comment]
> What's the file format of the texture file you're trying to import? Could you upload it or post a link?
> 
> Also try [BrawlCrate](https://github.com/soopercool101/BrawlCrate) and see if it's fixed there.

Well I used png for them. The files were from the textures of Mario Kart wii and I used them in sketchup. I used szs explorer to get the pictures out. 
[pics.zip](https://github.com/libertyernie/brawltools/files/4673207/pics.zip)

**Comment by WeeGee-mc** [comment]
> What's the file format of the texture file you're trying to import? Could you upload it or post a link?
> 
> Also try [BrawlCrate](https://github.com/soopercool101/BrawlCrate) and see if it's fixed there.

I have tried brawlcrate as well, however it has the same glitch from box.

**Comment by libertyernie** [comment]
I think I've got a fix (#232). I'll run it past the BrawlCrate author(s) too.
