### ISSUE TITLE
Float conversion error in COLLADA file

### ISSUE THREAD

**Issue by uyjulian** [libertyernie/brawltools#238]
There is a float conversion error resulting in the incorrect output `-..`.

E-mail me for a sample file.

**Comment by uyjulian** [comment]
This appears to be a `wine-mono` issue.

**Comment by libertyernie** [comment]
Out of curiosity, do you think there's anything that can be fixed in brawlbox so it works on mono on wine?

I know BrawlLib in general makes a lot of assumptions that the architecture is 32-bit (usually assuming that pointers can be converted to 32-bit integers)

**Comment by uyjulian** [comment]
Don't use `(0.0).ToString(CultureInfo.InvariantCulture.NumberFormat)` and instead use an alternative method for converting float/double into string.
