### ISSUE TITLE
Updater typo maybe

### ISSUE THREAD

**Issue by iGlitch** [libertyernie/brawltools#39]
Downloaded hotfix 2 and it prompted to update to hotfix 1.
I haven't checked how the source works yet, but it might be last line on here to help https://github.com/libertyernie/brawltools/blob/master/BrawlBox/Properties/AssemblyInfo.cs

**Comment by BlackJax96** [comment]
There is no v0.75b Hotfix 2, though.
It goes v0.75, 75h1, 75h2, 75b, 75b1.

The updater matches a string in MainForm.cs to the tag of the release on the repo, so it wouldn't have anything to do with the assembly info (although the version naming conventions will probably have to change sometime, v0.#letter only supports two revision types).

Are you sure you're not updating from v0.75 hotfix 2 (old) to v0.75b hotfix 1 (the most recent)?

**Comment by iGlitch** [comment]
Yeah, you were right. I was on 0.75, not b.
I had gotten http://forums.kc-mm.com/Gallery/BrawlView.php?Number=207827 and assumed it was the current version as the thread states, but I guess it's current stable? w/e. 
All is well now, thanks for the clarification.
