### ISSUE TITLE
Cannot save edits to model animations 

### ISSUE THREAD

**Issue by secretchaos1** [libertyernie/brawltools#42]
Upon trying to save any edits to model animations (chr0) the error "Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index" occurs.
This seems to only happen in 0.75b (unsure of other revisions of 0.75) however older versions of brawlbox can still save the animations correctly.

**Comment by BlackJax96** [comment]
What's the call stack? I tried making a test animation and didn't get any errors

**Comment by secretchaos1** [comment]
I'm not sure how to find that. All that comes up is this:
http://screenshooter.net/99992442/xygeeoc
And then the file doesn't save. The program doesn't crash, it just doesn't save.

**Comment by BlackJax96** [comment]
Oh. Can you tell me exactly what to do to reproduce the problem?

**Comment by secretchaos1** [comment]
It's happened with a couple motionetc files I've tried to edit. I'll upload the Little Mac animations that I was editing in the screenshot as an example, any time I've added a new bone target to them and tried to save I'd get that message.
Here's the example file: https://www.mediafire.com/?qo43b85bklo0bke

**Comment by BlackJax96** [comment]
Ok cool, I got it to throw the error. Thanks, I should have this fixed soon.

**Comment by secretchaos1** [comment]
Awesome, glad I could help
