### ISSUE TITLE
[0.77] Changed interface for audio player

### ISSUE THREAD

**Issue by Exagone313** [libertyernie/brawltools#58]
Hi,

The audio player just changed in this new version, but it is not perfect, everything is collapsed and not centered, and the time progress indicator is blinking.
Please revert back to what was before, because your new interface does not give something more.

**Comment by libertyernie** [comment]
Could you attach a screenshot?

**Comment by Exagone313** [comment]
For the blinking thing, I can't screenshot that. But here are screenshots for both version.
![v0.76b](https://cloud.githubusercontent.com/assets/11819703/16269209/b14dca48-3891-11e6-8f6d-96d5c4a0a640.png) 
![v0.77](https://cloud.githubusercontent.com/assets/11819703/16269221/bd4837c0-3891-11e6-96ef-71d83efc9fa5.png)

**Comment by libertyernie** [comment]
I originally changed it because it looked wrong on Windows 10, but now it looks like I can fix that by applying AutoScaleMode=None. So I'll change it back.
Apparently the flickering happens when the label is docked in the container... strange!
