### ISSUE TITLE
Help with ADPCM decoder

### ISSUE THREAD

**Issue by Wohlstand** [libertyernie/brawltools#61]
Hello!
I'm a developer of own platform game engine. For my purposes I was been forked C coded SDL Mixer 2.0 audio library to fix some bugs and imperfections myself and add support of more audio formats.

This library had:
- MP3 (libMAD)
- WAV/VOC (own parsing code)
- OGG (libOGG)
- FLAC (libFLAC)
- MIDI (Native Windows / OS-X / Haiku MIDI inreface / Timidity)
- ModPlug (most of tracker formats support)

Added by me:
- Support of loop-tags (LOOPSTART and LOOPEND/LOOPLENGHT) for OGG files
- GME (support of NSF, SPC, HES, etc.)
- Additional MIDI driver - libADLMIDI (plays MIDI's with emulated OPL3 chip. Only one MIDI-library which supports loop tags. Also can play Wolf3D IMF-files)

I thinking to add support of playing BRSTM's too, but at first I need to correctly decode ADPCM which I see in your code. Can you shortly describe me which files I should dig to learn ADPCM decoding algorithm? I going to make a decoding library in C from scratch to take it into my SDL Mixer fork.

Source of library: https://github.com/Wohlhabend-Networks/PGE-Project/tree/master/_Libs/SDL2_mixer_modified
Library in action (a music player program based on this library): http://wohlsoft.ru/docs/_builds/PGE_MusPlay/pge-musplay-win32.zip

**_Small trivia:**_
Anyway, OGG compression is much better than ADPCM (and in comparison with MP3, it doesn't hurts quality a lot), even I implemented loop tags support to have true looping musics in my library fork. But I still need to have right ADPCM decoder to make a BRSTM -> OGG converter with automatic adding of loop tags.

**Comment by libertyernie** [comment]
vgmstream can also play BRSTM and related formats, and I've heard that its decoder is a little bit better. That's written in C so you might even be able to integrate it somehow.
If you want to look at BrawlLib's RSTM decoder, I'd start in BrawlLib.Wii.Audio.ADPCMStream.GetStreams (line 27 of ADPCMStream.cs). It takes a pointer to the RSTM header and returns an array of streams (usually there is just one, and it can be mono or stereo.) The ADPCMStream object you get back has methods like ReadSamples, SamplePosition, etc.

P.S. if you have support for WAV files, you might want to add support for the looping WAV files (smpl chunk) that vgmstream's test.exe can output - it's nice to use as an intermediate format if you ever have to.

**Comment by Wohlstand** [comment]
Thanks for describing, and I'll checked vgmstream library, but unfortunately it lacks reading from memory, therefore I must to implement that myself. Anyway I have to implement some proxy from SDL_RWops to VGMSTREAM's file reading API, but even is possible just copy and adapt some code to read files via SDL_RWops directly

P.S. About WAV's, I have some code to do loops of WAV's which made by original developers of SDL Mixer library, but after I made my own resampler (because internal SDL2's in some cases producing a noice instead of music), it works not so correctly, even because I bufferizing resampled chunk's part (because function where that doing, is required ability to request chunk of any size and don't force use a fixed-size chunks).

**Comment by Wohlstand** [comment]
Hi there, sorry for keeping this issue being so stale, gonna close it, the question has been answered already, and I didn't took the actual work on things yet, proably will do something later, because it's not so important, however, I got an another idea which will go as a new issue.
