### ISSUE TITLE
Just a quick question...

### ISSUE THREAD

**Issue by DeckOfNoobs** [libertyernie/brawltools#66]
Is it okay if I include your program in a Splatoon Hacking All-In-One (Since BralwBox works with Splatoon files)? The All-In-One is here: https://github.com/MCMiners9/Splat-AIO

**Comment by libertyernie** [comment]
I'm OK with it.
How about you, @BlackJax96 / @Sammi-Husky ?

**Comment by Sammi-Husky** [comment]
I'm fine with it as well.

**Comment by BlackJax96** [comment]
I have no problem with it.

**Comment by DeckOfNoobs** [comment]
OK, thanks.
