### ISSUE TITLE
Scale

### ISSUE THREAD

**Issue by kalebsanders007** [libertyernie/brawltools#69]
Scaling a bone in brawlbox shows up in brawl box but doesnt scale on a wii

**Comment by libertyernie** [comment]
It's hard to say what the problem is without more details. That being said, have you checked the animation for the model? I know for stages at least, the transformation/rotation/scale has to be applied in the animation, not directly on the model.

**Comment by kalebsanders007** [comment]
im using well-endowed zelda and it doesnt work, i did what the instructions said, and it worked in the last brawl box update. (please dont judge me)

**Comment by kalebsanders007** [comment]
I probobly should have made it more clear, could you add it so you can hightlight animations/bones like you can in windows
![image](https://cloud.githubusercontent.com/assets/16215326/18071892/c85cb92a-6e1e-11e6-9f7d-2642037248af.png)

**Comment by libertyernie** [comment]
I don't know much about the 3D model viewer, so I won't be of much help.

**Comment by kalebsanders007** [comment]
ok
Could you add this feature, because it would make it way easier to edit multiple bones, animations, lightings, etc. faster

**Comment by kalebsanders007** [comment]
could you add it so you can hightlight animations/bones like you can in windows
![image](https://cloud.githubusercontent.com/assets/16215326/18071892/c85cb92a-6e1e-11e6-9f7d-2642037248af.png)

**Comment by kalebsanders007** [comment]
It would help tremendously with many animations imo =D

**Comment by kalebsanders007** [comment]
plus, it makes editing muliple things less tedious

**Comment by kalebsanders007** [comment]
Thanks for listening to me ramble :)
