### ISSUE TITLE
[request] port from Direct Sound to OpenAL

### ISSUE THREAD

**Issue by Tcll** [libertyernie/brawltools#72]
Finally tried opening a brstm file with the latest version, but to no avail, it still instantly crashes...

I assume this has to do with DirectX issues on wine but I can't say for sure...

But I'm not reporting an issue, since I still don't have internet yet... :P 

OpenAL does just as good, if not better, and works on everything.

**Comment by libertyernie** [comment]
Are there any guides or tutorials on playing looping audio with OpenAL in C#? The only tutorials I've seen so far are for loading the whole audio data in the buffer and playing it.
BrawlLib's code does some pretty low-level stuff with DirectSound buffers right now, so I think it might be easier to move up to BrstmConverterDialog and replace AudioBuffer there.

**Comment by Tcll** [comment]
Haha, tbh, idk... haven't had internet to look, and this phone isn't mine...
I only suggested because I'm working on a python wrapper for it for UGE, and know it's really good.

Heck, minecraft uses it, and so far, it's the only game I have which utilizes my rear speakers flawlessly.
not even Xonotic can top that.

I personally don't see anything wrong with the audio buffer being in "your" control...
to me, that just screams more control, allowing you to do more.

Bleh... in any case, it was just a suggestion for flawless compatibility. ;)

**Comment by libertyernie** [comment]
Yeah, using something besides direct sound would be nice for 64-bit compatibility anyway. Of course we can always build as 32-bit on Windows, but...

**Comment by Tcll** [comment]
Heh, I'm kinda stuck in the 32bit Windows/wine rut myself, due to a lack of portable python interpreters, so I understand ;)

But hey, if you understand the concept, looping audio is actually really easy...

I'm still working on that little Pikachu Voice Simulator project, but I used PyAudio to play raw audio samples from bu8 to bf32...
So yea I had to build those samples from a sine wave...

Once you understand how audio works, trust me, you'll want full control over everything ;)

**Comment by Tcll** [comment]
Stupid glitcy browser, or touch screen driver...
I hate phones >_<

**Comment by Wohlstand** [comment]
Tcll, if android, try OctoDroid

**Comment by libertyernie** [comment]
Any tips on getting OpenAL + OpenTK to work on windows?
I tried downloading http://kcat.strangesoft.net/openal.html and saving the DLL as openal32.dll, but I get an InvalidOperation error from OpenAL when trying to create a buffer.

**Comment by Tcll** [comment]
@Wohlstand If this was my phone, I'd have linux installed on it... Android can suck it like Windows ;)
mother don't want me installing anything on her phone after Discord supposedly corrupted her last phone...
(I disagree, I think it was the poor excuse for a FAT32 driver on Linux that did the damage, or the phone just died, which her model is known to do)

Anyways...
@libertyernie sadly, that's out of my league...
But I might have an idea, being the very reason you need OpenTK to wrap OpenGL for C#...

Perhaps there's a wrapper for OpenAL... >.>

**Comment by Sammi-Husky** [comment]
Iirc OpenTK itself included some wrappers for OpenAL that we should be able to use.

**Comment by libertyernie** [comment]
Yeah, there are OpenAL wrappers in OpenTK. I couldn't get them to work on this PC, though. Maybe I should try a sample app in MonoDevelop on Linux and see if that works?

Right now BrawlBox should be able to open BRSTMs on 32-bit Mono (without Wine), but not play them. I added a commit last night to make that work in 64-bit Mono too, although other things are still broken in that case.

**Comment by libertyernie** [comment]
OK, I got this example to work: https://github.com/opentk/opentk/blob/master/Source/Examples/OpenAL/1.1/Playback.cs
Next step is to figure out how to make it loop, etc.

**Comment by libertyernie** [comment]
OpenAL should work in the next release on Linux and Mac out of the box.
On Windows it'll just keep using DirectSound if OpenAL isn't available.
