### ISSUE TITLE
Command line arguments and fade for BRSTMs

### ISSUE THREAD

**Issue by undying-fish** [libertyernie/brawltools#88]
Unsure of whether this exists already but could there be a way to open BRSTM files in particular through BrawlBox and have them autoplay and loop? Also, how hard is it to have an option to fade out when stopped as in Brawl's sound test as opposed to a flat stop like there is now?

**Comment by libertyernie** [comment]
I bet I could add options like this into BrawlBox, but I'd recommend using vgmstream's text.exe instead - it has options like these already, and it's better at decoding BRSTMs than BrawlBox is. The only catch is that I don't think it can actually play audio through the speakers, so you'd need to either pipe its output to another program (-p) or play the dump.wav file that it generates.

The latest vgmstream source is at https://gitlab.kode54.net/kode54/vgmstream. If you can't find a copy of test.exe, I have one at https://github.com/libertyernie/LoopingAudioConverter/tree/master/LoopingAudioConverter/tools_win32/vgmstream that's about a year old.

**Comment by undying-fish** [comment]
That's excellent to know, thank you for getting back to me. Might message you about another question I've got directly.

**Comment by libertyernie** [comment]
It would theoretically be easier to use the vgmstream source code for that, which I think is in C. That said, I don't know exactly how the vgmstream code works.
Either way, I think you would have to compile a program that's an app or something, not just a command line executable.
