### ISSUE TITLE
Batch convert .pcs <-> .pac files with optional subfolder inclusion

### ISSUE THREAD

**Issue by Ebola16** [libertyernie/brawltools#92]
- [x] Batch convert (pac to pcs)
- [x] Batch convert (pcs to pac)
- [x] Optional subfolder inclusion

It would be convenient if Brawlbox could batch convert .pcs <-> .pac files.

Fyi, gbalzss can batch convert .pcs -> .pac (https://elitesmashhackers.wordpress.com/2009/07/16/enough-with-lz77ex/). Using gbalzss to convert .pac -> .pcs will crash Brawlbox.
I haven't tested the source code but it is likely here https://github.com/comex/somestuff/tree/master/gbalzss_compressor_tool

**Comment by libertyernie** [comment]
This sounds like something I could figure out how to do.

**Comment by libertyernie** [comment]
I added a Python plugin (using the plugin system Sammi put together) that asks for a folder and then scans it and its subfolders for pac files, and makes pcs versions of all of them (in the same folder as the originals.) How's that sound?

**Comment by Ebola16** [comment]
I tested your python plugin with a few dozen files and it seemed to properly mass convert .pac -> .pcs conversion.

Would you be able to make another plugin that supports mass .pcs -> .pac conversion?
After some more testing, gbalzss can't decode ExtendedLZ77 so this is another job for Brawlbox.

**Comment by libertyernie** [comment]
Just make a copy of the python file, and switch the from_ext to .pcs and the to_ext to .pac.

**Comment by Ebola16** [comment]
I tried that but Brawlbox just copies the file with a different extension when converting .pcs -> .pac
It does not change the root ARC entry compression type to "None"

(The proper root ARC entry compression change occurs in your .pac -> .pcs plugin)

**Comment by libertyernie** [comment]
Huh. I wonder why that is? I'll look for a way to fix it.

**Comment by libertyernie** [comment]
OK, I updated the plugin. Now it converts from .pcs -> .pac (just swap the extensions to go the other way), and when converting from .pac, it sets the compression type to None first.

**Comment by Ebola16** [comment]
Would you be opposed to keeping both plugins? They would be:
Batch convert (pac to pcs)
Batch convert (pcs to pac)

Both plugins seem to work properly now. I exported your original Batch convert (pac to pcs) plugin.
[Batch convert (pac to pcs).zip](https://github.com/libertyernie/brawltools/files/637054/Batch.convert.pac.to.pcs.zip)

**Comment by libertyernie** [comment]
Yeah, I guess having just one and not the other makes it kind of arbitrary. I'll put them both in.

**Comment by Ebola16** [comment]
Also, an "include subfolders" option would be convenient for both plugins. I can file a follow-up issue if this is time-consuming or difficult to implement.

**Comment by libertyernie** [comment]
The BrawlBox API doesn't have an elegant way to ask for options like this (yet) - maybe at some point I'll add one.
Until then, you can change the plugin to not include subfolders, if that's what you do more often, by adding a "break" at the same level as "for file in files:"

	for root, dirs, files in os.walk(dir):
		for file in files:
			...
		break

Or maybe I should change the plugin to have the break, and allow people to remove it?

**Comment by Ebola16** [comment]
I think most users would want subfolders included by default, as they can make batch conversions of Brawl's entire .../fighter folder. Perhaps renaming the plugins to "Batch convert pac to pcs (includes subfolders)" and "Batch convert pcs to pac (includes subfolders)" would help?

Optional subfolder inclusion would be nice but isn't an immediate necessity. I'll keep this issue open and rename it since you may add this functionality in the future.

Thank you for help!

**Comment by Ebola16** [comment]
BrawlBox.csproj didn't properly update after renaming those files.

**Comment by libertyernie** [comment]
Oops! I'll get that taken care of in a bit.

**Comment by Ebola16** [comment]
a88c45499c57b7a91ca5ff336e28d427b3d36339 addresses optional subfolder inclusion.
Function wise, LGTM!
