### ISSUE TITLE
Make redirect entries exportable / replaceable

### ISSUE THREAD

**Issue by Ebola16** [libertyernie/brawltools#97]
Although redirect entries contain no data, they do have a RedirectIndex that can be manually edited. I haven't researched the redirect entries in much detail but being able to import / export them could aid in redirecting indices.

**Comment by Sammi-Husky** [comment]
Redirect indexes just tell the game "If you look here, actually look THERE instead". They're used for item's and Item costume's extensively. To add a new redirect, just add a new ARC entry via right click and set the redirect index. When saving it will be changed into a redirect.

Allowing BBox to export empty files would be useless and wouldn't work anyways, and the ARC header where the redirect index is doesn't show up in child node data anyways afaik so using them with export/replace wouldn't do anything
